# Generated by Django 5.2.7 on 2025-10-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(max_length=100)),
                ('prize_description', models.TextField(blank=True, null=True)),
                ('prize_image', models.ImageField(blank=True, null=True, upload_to='prizes/')),
                ('draw_date', models.DateField()),
                ('number_winner', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaffleNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='raffle.participant')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='raffle.raffle')),
            ],
            options={
                'unique_together': {('number', 'raffle')},
            },
        ),
    ]
